import { Citation } from '../types';

/**
 * Exports an answer with verified citations into a downloadable HTML/PDF or formatted text file.
 */
export function exportAnswerAsFile(
  question: string,
  answer: string,
  citations: Citation[] = [],
  contractName: string = 'Contract'
) {
  const formattedCitations = citations
    .map(
      (c, idx) =>
        `${idx + 1}. Page ${c.page} (${c.section || 'General'}): "${c.quote}" [${c.verified ? 'Verified' : 'Unverified'}]`
    )
    .join('\n');

  const content = `===============================================================
LEXICONTRACT ANALYSIS REPORT
Contract: ${contractName}
Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
===============================================================

USER QUESTION:
${question}

---------------------------------------------------------------
ANALYSIS ANSWER:
${answer.replace(/#{1,4}\s+/g, '').replace(/\*\*/g, '')}

---------------------------------------------------------------
VERIFIED CONTRACT CITATIONS:
${formattedCitations || 'No specific citations attached.'}

===============================================================
Report generated by LexiContract AI Legal Intelligence.
`;

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Analysis_${contractName.replace(/\.[^/.]+$/, '')}_${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
